# app.yaml - Complete application in one file
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  config.properties: |
    server.port=8080
    app.name=my-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: your-docker-repo/your-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_FILE
          value: "/config/config.properties"
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: my-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
