name: CI/CD Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Backend - Install dependencies
      run: |
        cd Sea_sos-backend
        npm install

    - name: Backend - Run tests
      run: |
        cd Sea_sos-backend
        npm test || echo "No tests configured"

    - name: Frontend - Install dependencies
      run: |
        cd Sea_sos-frontend
        npm install
        npm install jwt-decode
        npm install --save-dev @babel/plugin-proposal-private-property-in-object

    - name: Frontend - Build
      run: |
        cd Sea_sos-frontend
        CI=false npm run build

    - name: Build Docker Images
      run: |
        docker build -t sea-sos-backend ./Sea_sos-backend
        docker build -t sea-sos-frontend ./Sea_sos-frontend

    - name: Success
      run: echo "✅ CI Pipeline completed successfully!"
